# Generated by Django 5.0.6 on 2024-12-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0009_alter_mcmodel_reg_date_alter_wordsmodel_reg_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListSentenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_list', models.JSONField(blank=True, null=True)),
                ('eibun', models.CharField(blank=True, max_length=250, null=True)),
                ('wayaku', models.CharField(blank=True, max_length=200, null=True)),
                ('bunpo', models.TextField(blank=True, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('source_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wlist.wordsmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
