# Generated by Django 5.0.6 on 2024-12-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0010_listsentencemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listsentencemodel',
            old_name='source_id',
            new_name='source',
        ),
    ]
