# Generated by Django 5.0.6 on 2024-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlist', '0012_listsentencemodel_eval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsentencemodel',
            name='fusen',
            field=models.BooleanField(default=True),
        ),
    ]
